version: '3'
services:
  app:
    image: your-node-app-image:latest
    ports:
      - "8080:8080"
    # Other configurations for your Node.js app

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - app

