# Use the official Nginx base image
FROM nginx:latest

# Remove the default configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy your custom configuration to the conf.d directory
COPY nginx.conf /etc/nginx/conf.d/

# Expose the port that Nginx will listen on
EXPOSE 80

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]


